### ISSUE TITLE
Unable to add library: Check the ID and access permissions and try again

### ISSUE THREAD

**Issue by SimonEast** [simula-innovation/gas-underscore#2]
I'm attempting to add this library to my Apps Script, but am getting an error:

![image](https://user-images.githubusercontent.com/813734/123357659-4cd4b900-d5ad-11eb-93c7-cc8c72e7ee4f.png)

Is this still supported?

(BTW, I followed the same instructions for [LodashGS](https://github.com/contributorpw/lodashgs) and that seemed to work.)

**Comment by adapi** [comment]
New script ID is 1PcEHcGVC1njZd8SfXtmgQk19djwVd2GrrW1gd7U5hNk033tzi6IUvIAV

**Comment by SimonEast** [comment]
Great, thank you!
